name: Extralibs Packaging

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest"]
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          activate-environment: conda_env

      - name: Create Conda environment and install libraries
        shell: bash -el {0}
        run: |
          conda install --file requirements.txt -y

      - name: Prepare extlibs
        shell: bash -el {0}
        run: |
          if [ ${{ matrix.os }} == 'windows-latest' ]; then
            SITE_PACKAGES_PATH=$CONDA_PREFIX/Lib/site-packages
          else
            SITE_PACKAGES_PATH=$CONDA_PREFIX/lib/python${{ matrix.python-version }}/site-packages
          fi
          mv $SITE_PACKAGES_PATH ./extlibs
          rm -rf ./extlibs/plotly* ./extlibs/pip* ./extlibs/setuptools* ./extlibs/panel* ./extlibs/bokeh* ./extlibs/babel* ./extlibs/rtree*

      # create a zip file with the extlibs
      - uses: vimtor/action-zip@v1
        with:
          files: extlibs
          dest: extlibs_${{ matrix.os }}_py${{ matrix.python-version }}.zip

      # upload the zip file as an artifact
      - name: Upload extlibs zip artifact
        uses: actions/upload-artifact@v2
        with:
          name: extlibs_${{ matrix.os }}_py${{ matrix.python-version }}
          path: ${{ github.workspace }}/extlibs_${{ matrix.os }}_py${{ matrix.python-version }}.zip

  packages:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
