name: Extralibs Packaging

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.9"]
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          activate-environment: conda_env

      - name: Create Conda environment and install libraries
        shell: bash -el {0}
        run: |
          conda install -c conda-forge gdal -y

      - name: Zip the site-packages
        shell: bash -el {0}
        if : matrix.os == 'ubuntu-latest' || matrix.os == 'macOS-latest'
        run: |
            echo "Conda prefix $CONDA_PREFIX"
            zip -r extlibs_${{ matrix.os }}_py${{ matrix.python-version }}.zip $CONDA_PREFIX/lib/python${{ matrix.python-version }}/site-packages

      - name: Zip the site-packages
        shell: bash -el {0}
        if : matrix.os == 'windows-latest'
        run: |
            zip -r extlibs_${{ matrix.os }}_py${{ matrix.python-version }}.zip $CONDA_PREFIX/Lib/site-packages

      - name: Upload extlibs zip artifact
        uses: actions/upload-artifact@v2
        with:
          name: extlibs_${{ matrix.os }}_py${{ matrix.python-version }}
          path: ./extlibs_${{ matrix.os }}_py${{ matrix.python-version }}.zip
